<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="socialnetwork" nsURI="org.eclipse.emf.odysseus.models.socialnetwork"
    nsPrefix="socialnetwork">
  <eSubpackages name="activity" nsURI="org.eclipse.emf.odysseus.socialnetwork.activity"
      nsPrefix="activity">
    <eClassifiers xsi:type="ecore:EClass" name="Post" eSuperTypes="#//activity/Contribution">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isRepostOf" eType="#//activity/Post"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachedMedia" upperBound="-1"
          eType="#//media/MediaData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mentions" upperBound="-1"
          eType="#//user/Person"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inGroup" eType="#//user/Group"
          eOpposite="#//user/Group/posts"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//activity/Visibility"
          defaultValueLiteral="EVERYONE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reactions" upperBound="-1"
          eType="#//activity/Reaction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
          eType="#//activity/Comment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reaction" eSuperTypes="#//activity/Response">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//activity/ReactionType"
          defaultValueLiteral="LIKE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ReactionType">
      <eLiterals name="Like" value="1" literal="LIKE"/>
      <eLiterals name="Haha" value="2" literal="HAHA"/>
      <eLiterals name="Angry" value="3" literal="ANGRY"/>
      <eLiterals name="Sad" value="4" literal="SAD"/>
      <eLiterals name="Wow" value="5" literal="WOW"/>
      <eLiterals name="Love" value="6" literal="LOVE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
      <eLiterals name="Everyone" value="1" literal="EVERYONE"/>
      <eLiterals name="FriendsOfFriends" value="2" literal="FRIENDSOFFRIENDS"/>
      <eLiterals name="Friends" value="3" literal="FRIENDS"/>
      <eLiterals name="JustMe" value="4" literal="JUSTME"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//activity/Response">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inResponseTo" eType="#//activity/Comment"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Contribution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//user/Person"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Response" eSuperTypes="#//activity/Contribution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="post" eType="#//activity/Post"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="user" nsURI="org.eclipse.emf.odysseus.socialnetwork.user" nsPrefix="user">
    <eClassifiers xsi:type="ecore:EClass" name="Person">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="#//user/Gender"
          defaultValueLiteral="MALE"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthdate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberSince" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="marriedTo" eType="#//user/Person"
          unsettable="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
          upperBound="-1" eType="#//user/Person" eOpposite="#//user/Person/parents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="profilePicture" eType="#//media/MediaData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="friends" upperBound="-1"
          eType="#//user/Person"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
          eType="#//user/Person" eOpposite="#//user/Person/children"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="membershipInGroups" upperBound="-1"
          eType="#//user/Group" eOpposite="#//user/Group/members"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Gender">
      <eLiterals name="Male" value="1" literal="MALE"/>
      <eLiterals name="Female" value="2" literal="FEMALE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Group">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="admin" eType="#//user/Person"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#//user/Person" eOpposite="#//user/Person/membershipInGroups"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="posts" upperBound="-1"
          eType="#//activity/Post" eOpposite="#//activity/Post/inGroup"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="media" nsURI="org.eclipse.emf.odysseus.socialnetwork.media"
      nsPrefix="media">
    <eClassifiers xsi:type="ecore:EClass" name="MediaData">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//media/MediaType"
          defaultValueLiteral="IMAGE"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uploadDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MediaType">
      <eLiterals name="Image" value="1" literal="IMAGE"/>
      <eLiterals name="Video" value="2" literal="VIDEO"/>
      <eLiterals name="Audio" value="3" literal="AUDIO"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
